language: node_js
node_js:
  - "7"
before_script:
  - npm install -g loopback npm@latest
cache:
  directories:
    - "node_modules"
notifications:
  email:
    - go4taj@gmail.com
    - taj.ahmed@otssolutions.com